<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: todo.proto

namespace GPBMetadata;

class Todo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x8F\x06\x0A\x0Atodo.proto\"\x9E\x01\x0A\x0BTodoMessage\x12\x0A\x0A\x02id\x18\x01 \x01(\x09\x12\x0D\x0A\x05title\x18\x02 \x01(\x09\x12\x14\x0A\x0Cis_completed\x18\x03 \x01(\x08\x12.\x0A\x0Acreated_at\x18\x04 \x01(\x0B2\x1A.google.protobuf.Timestamp\x12.\x0A\x0Aupdated_at\x18\x05 \x01(\x0B2\x1A.google.protobuf.Timestamp\"D\x0A\x0FGetTodosRequest\x12\x14\x0A\x0Cis_completed\x18\x01 \x01(\x08\x12\x1B\x0A\x08ordering\x18\x02 \x01(\x0E2\x09.Ordering\"/\x0A\x10GetTodosResponse\x12\x1B\x0A\x05todos\x18\x01 \x03(\x0B2\x0C.TodoMessage\"\"\x0A\x11CreateTodoRequest\x12\x0D\x0A\x05title\x18\x01 \x01(\x09\"\x14\x0A\x12CreateTodoResponse\"D\x0A\x11UpdateTodoRequest\x12\x0A\x0A\x02id\x18\x01 \x01(\x09\x12\x0D\x0A\x05title\x18\x02 \x01(\x09\x12\x14\x0A\x0Cis_completed\x18\x03 \x01(\x08\"\x14\x0A\x12UpdateTodoResponse\"\x1F\x0A\x11DeleteTodoRequest\x12\x0A\x0A\x02id\x18\x01 \x01(\x09\"\x14\x0A\x12DeleteTodoResponse*\x1D\x0A\x08Ordering\x12\x07\x0A\x03ASC\x10\x00\x12\x08\x0A\x04DESC\x10\x012\xE4\x01\x0A\x04Todo\x121\x0A\x08GetTodos\x12\x10.GetTodosRequest\x1A\x11.GetTodosResponse\"\x00\x127\x0A\x0ACreateTodo\x12\x12.CreateTodoRequest\x1A\x13.CreateTodoResponse\"\x00\x127\x0A\x0AUpdateTodo\x12\x12.UpdateTodoRequest\x1A\x13.UpdateTodoResponse\"\x00\x127\x0A\x0ADeleteTodo\x12\x12.DeleteTodoRequest\x1A\x13.DeleteTodoResponse\"\x00B\x0E\xCA\x02\x0BApp\\GrpcGenb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

