"""create todo table

Revision ID: 951a5eebe8dc
Revises: 
Create Date: 2025-03-18 05:32:20.755645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '951a5eebe8dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('todo',
                  sa.Column('id', sa.String(), nullable=False),
                  sa.Column('title', sa.String(), nullable=False),
                  sa.Column('is_completed', sa.Boolean(), nullable=False),
                  sa.Column('created_at', sa.DateTime(timezone=True),
                            server_default=sa.text('now()'), nullable=True),
                  sa.Column('updated_at', sa.DateTime(timezone=True),
                            server_default=sa.text('now()'), nullable=True),
                  sa.PrimaryKeyConstraint('id')
                  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table('todo')
  # ### end Alembic commands ###
