"""alter todo table

Revision ID: e81e682440a9
Revises: 951a5eebe8dc
Create Date: 2025-03-18 05:35:56.651112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e81e682440a9'
down_revision: Union[str, None] = '951a5eebe8dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.alter_column('todo', 'created_at',
                  existing_type=postgresql.TIMESTAMP(timezone=True),
                  nullable=False,
                  existing_server_default=sa.text('now()'))
  op.alter_column('todo', 'updated_at',
                  existing_type=postgresql.TIMESTAMP(timezone=True),
                  nullable=False,
                  existing_server_default=sa.text('now()'))
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.alter_column('todo', 'updated_at',
                  existing_type=postgresql.TIMESTAMP(timezone=True),
                  nullable=True,
                  existing_server_default=sa.text('now()'))
  op.alter_column('todo', 'created_at',
                  existing_type=postgresql.TIMESTAMP(timezone=True),
                  nullable=True,
                  existing_server_default=sa.text('now()'))
  # ### end Alembic commands ###
