<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: todo.proto

namespace App\GrpcGen;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GetTodosRequest</code>
 */
class GetTodosRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool is_completed = 1;</code>
     */
    protected $is_completed = false;
    /**
     * Generated from protobuf field <code>.Ordering ordering = 2;</code>
     */
    protected $ordering = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $is_completed
     *     @type int $ordering
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Todo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool is_completed = 1;</code>
     * @return bool
     */
    public function getIsCompleted()
    {
        return $this->is_completed;
    }

    /**
     * Generated from protobuf field <code>bool is_completed = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsCompleted($var)
    {
        GPBUtil::checkBool($var);
        $this->is_completed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Ordering ordering = 2;</code>
     * @return int
     */
    public function getOrdering()
    {
        return $this->ordering;
    }

    /**
     * Generated from protobuf field <code>.Ordering ordering = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOrdering($var)
    {
        GPBUtil::checkEnum($var, \App\GrpcGen\Ordering::class);
        $this->ordering = $var;

        return $this;
    }

}

